### PR TITLE
[FEATURE] Click row to select/remove validator

### PR DESCRIPTION
**Pull request by stevenzeiler**
Clear selected validators on navigation to /#/validators

[TASK] relink h1 to home page

### CODE REVIEW

**Comment by stevenzeiler** [comment]
:+1:

**Comment by wilsonianb** [comment]
This makes it hard to tell that the validation public key and domain are links. Can something happen when they are moused over?

**Comment by stevenzeiler** [comment]
How about disabling the "hand" pointer unless mousing over a link?

**Comment by wilsonianb** [comment]
Let's try that

**Comment by stevenzeiler** [comment]
Okay give that a spin.

**Comment by wilsonianb** [comment]
I like that better. Minor nitpick: the + no longer needs the hand pointer

**Comment by wilsonianb** [comment]
Actually, can we only display the plus when the row is moused over?

**Comment by stevenzeiler** [comment]
I think the `+` should retain the hand pointer but it would be nice to try out displaying the `+` only when the row is moused over. I'll give it a shot.

**Comment by wilsonianb** [comment]
Is drag and drop out of the question?

**Comment by stevenzeiler** [comment]
:+1:

**Comment by wilsonianb** [comment]
Last thing...
Can we also make the domain a link on the validator page?

**Comment by stevenzeiler** [comment]
Yes

**Comment by wilsonianb** [comment]
LGTM :+1:

**Pull request merged**
