### PR TITLE
[TASK] Use + and - buttons for selecting UNL

### PR DESCRIPTION
**Pull request by stevenzeiler**
+r

### CODE REVIEW

**Comment by wilsonianb** [comment]
This appears to change the public key to not be clickable.

**Comment by stevenzeiler** [comment]
Correct, you now must click the (+) or (-) buttons to add or remove a validator from the UNL

**Comment by wilsonianb** [comment]
Ok, can you clarify that in the commit message and fix the typo in the other commit message?

**Comment by stevenzeiler** [comment]
The original commit message has been updated.

**Pull request closed without merging**
